import About from '@/layouts/About';
import Blog from '@/layouts/Blog';
import Header from '@/layouts/Header';
import Practice from '@/layouts/Practice';
import Team from '@/layouts/Team';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Axbridge Partners</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
        <About />
        <Practice />
        <Team />
        <Blog />
      </main>
    </>
  );
}
